// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-W0y0rmjdBCb_ZizylvcfR9hoZgxq68c',
    appId: '1:1070505142813:web:7a6c064b647fcb76a8b4f4',
    messagingSenderId: '1070505142813',
    projectId: 'skillexchange-77b7d',
    authDomain: 'skillexchange-77b7d.firebaseapp.com',
    databaseURL: 'https://skillexchange-77b7d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skillexchange-77b7d.firebasestorage.app',
    measurementId: 'G-7NLXKG3TLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCoGUK32CGqBOtq5bFgcrDR3Ypkf54lNI',
    appId: '1:1070505142813:android:b44c900160cf691ca8b4f4',
    messagingSenderId: '1070505142813',
    projectId: 'skillexchange-77b7d',
    databaseURL: 'https://skillexchange-77b7d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skillexchange-77b7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBobVTwQxG3pJyOZMhHrQc7uojhaUgQui4',
    appId: '1:1070505142813:ios:9bf88550133dc3dfa8b4f4',
    messagingSenderId: '1070505142813',
    projectId: 'skillexchange-77b7d',
    databaseURL: 'https://skillexchange-77b7d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skillexchange-77b7d.firebasestorage.app',
    iosBundleId: 'com.example.talentloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBobVTwQxG3pJyOZMhHrQc7uojhaUgQui4',
    appId: '1:1070505142813:ios:9bf88550133dc3dfa8b4f4',
    messagingSenderId: '1070505142813',
    projectId: 'skillexchange-77b7d',
    databaseURL: 'https://skillexchange-77b7d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skillexchange-77b7d.firebasestorage.app',
    iosBundleId: 'com.example.talentloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-W0y0rmjdBCb_ZizylvcfR9hoZgxq68c',
    appId: '1:1070505142813:web:6277534eb5d17012a8b4f4',
    messagingSenderId: '1070505142813',
    projectId: 'skillexchange-77b7d',
    authDomain: 'skillexchange-77b7d.firebaseapp.com',
    databaseURL: 'https://skillexchange-77b7d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skillexchange-77b7d.firebasestorage.app',
    measurementId: 'G-FC1XP9NJ0W',
  );
}
